[build]
  publish = "dist"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-cache-folder"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https://res.cloudinary.com *://*.webmention.io *://*.amazonaws.com; manifest-src 'self'; script-src 'self' 'sha256-FTeJwfs/oKoQ8Y0jaWpkYtJZMy453pCuLlhQ+SGmx7Q='; connect-src 'self' https://res.cloudinary.com; img-src https://res.cloudinary.com *://*.webmention.io *://*.amazonaws.com 'self'; style-src 'self'; form-action 'self' https://juanfernandes.us14.list-manage.com; frame-ancestors 'none';"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "interest-cohort=()"

# Redirects

[[redirects]]
  from = "/cms"
  to = "https://app.forestry.io/dashboard/"
  status = 200
  force = true

[[redirects]]
  from = "/blog/working-an-inside-IR35-contract"
  to = "/blog/working-an-inside-ir35-contract"
  status = 301

[[redirects]]
  from = "/index.php"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/about/index.php"
  to = "/about/index.html"
  status = 301

[[redirects]]
  from = "/contact/index.php"
  to = "/contact/index.html"
  status = 301

[[redirects]]
  from = "/now/index.php"
  to = "/now/index.html"
  status = 301

[[redirects]]
  from = "/blog/index.php"
  to = "/blog/index.html"
  status = 301

[[redirects]]
  from = "/work/index.php"
  to = "/work/index.html"
  status = 301

[[redirects]]
  from = "/testimonials/index.php"
  to = "/testimonials/index.html"
  status = 301

[[redirects]]
  from = "/work/index.php"
  to = "/work/index.html"
  status = 301

[[redirects]]
  from = "/blog/category/personal"
  to = "/tags/personal/"
  status = 301

[[redirects]]
  from = "/blog/tags/personal/"
  to = "/tags/personal/"
  status = 301

[[redirects]]
  from = "/blog/category/design"
  to = "/tags/design/"
  status = 301

[[redirects]]
  from = "/blog/tags/design/"
  to = "/tags/design/"
  status = 301

[[redirects]]
  from = "/blog/category/development"
  to = "/tags/development/"
  status = 301

[[redirects]]
  from = "/blog/tags/development/"
  to = "/tags/development/"
  status = 301

[[redirects]]
  from = "/blog/notes.php"
  to = "/notes/"
  status = 301

[[redirects]]
  from = "/rss"
  to = "/rss/feed.xml"
  status = 301

[[redirects]]
  from = "/blog/2016-12-09-adding-svg-icons-to-a-sprite-with-perch-cms/"
  to = "/blog/adding-svg-icons-to-a-sprite-with-perch-cms/"
  status = 301

[[redirects]]
  from = "/2018-01-09-twenty-seventeen/"
  to = "/blog/twenty-seventeen/"
  status = 301

[[redirects]]
  from = "/blog/2019-04-16-weeknotes-10/"
  to = "/notes/weeknotes-10/"
  status = 301

[[redirects]]
  from = "/blog/exploring-the-benefits-if-http-2/"
  to = "/blog/exploring-the-benefits-of-http-2/"
  status = 301
