[build]
  publish = "dist"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-cache-folder"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/api/:splat'
  status = 200

[[redirects]]
  from = "/blog/2018-a-year-in-review/"
  to = "/blog/2018-year-in-review/"
  status = 301

[functions]
  external_node_modules = ["express", "vm2"]
  node_bundler = 'esbuild'
