[build]
  publish = "dist"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-cache-folder"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/api/:splat'
  status = 200

[[redirects]]
  from = "/blog/2018-a-year-in-review/"
  to = "/blog/2018-year-in-review/"
  status = 301

[[redirects]]
  from = "/notes/bye-bye-gmail/"
  to = "/stream/bye-bye-gmail/"
  status = 301

[[redirects]]
  from = "/notes/changelog-add-other-links-to-the-footer/"
  to = "/stream/changelog-add-other-links-to-the-footer/"
  status = 301

[[redirects]]
  from = "/notes/created-my-first-npm-package/"
  to = "/stream/created-my-first-npm-package/"
  status = 301

[[redirects]]
  from = "/notes/degoogling-is-the-same-as-jailbreaking-apparently/"
  to = "/stream/degoogling-is-the-same-as-jailbreaking-apparently/"
  status = 301

[[redirects]]
  from = "/notes/estimote-lte-beacons-developer-kit/"
  to = "/stream/estimote-lte-beacons-developer-kit/"
  status = 301

[[redirects]]
  from = "/notes/firefox-focus/"
  to = "/stream/firefox-focus/"
  status = 301

[[redirects]]
  from = "/notes/google-hangouts/"
  to = "/stream/google-hangouts/"
  status = 301

[[redirects]]
  from = "/notes/google-pay/"
  to = "/stream/google-pay/"
  status = 301

[[redirects]]
  from = "/notes/indieweb-tweets/"
  to = "/stream/indieweb-tweets/"
  status = 301

[[redirects]]
  from = "/notes/native-disclosure-element-work-in-instapaper-app/"
  to = "/stream/native-disclosure-element-work-in-instapaper-app/"
  status = 301

[[redirects]]
  from = "/notes/new-adventures-2020/"
  to = "/stream/new-adventures-2020/"
  status = 301

[[redirects]]
  from = "/notes/new-pallet-project/"
  to = "/stream/new-pallet-project/"
  status = 301

[[redirects]]
  from = "/notes/off-facebook/"
  to = "/stream/off-facebook/"
  status = 301

[[redirects]]
  from = "/notes/performance-what-performance/"
  to = "/stream/performance-what-performance/"
  status = 301

[[redirects]]
  from = "/notes/replacing-my-phone-s-os/"
  to = "/stream/replacing-my-phone-s-os/"
  status = 301

[[redirects]]
  from = "/notes/switching-to-firefox-focus/"
  to = "/stream/switching-to-firefox-focus/"
  status = 301

[[redirects]]
  from = "/notes/version-2-of-my-website-went-live-last-week/"
  to = "/stream/version-2-of-my-website-went-live-last-week/"
  status = 301

[[redirects]]
  from = "/blog/working-an-inside-IR35-contract"
  to = "/blog/working-an-inside-ir35-contract/"
  status = 301

[[redirects]]
  from = "/blog/category/personal"
  to = "/tags/personal/"
  status = 301

[[redirects]]
  from = "/blog/tags/personal/"
  to = "/tags/personal/"
  status = 301

[[redirects]]
  from = "/blog/category/design"
  to = "/tags/design/"
  status = 301

[[redirects]]
  from = "/blog/tags/design/"
  to = "/tags/design/"
  status = 301

[[redirects]]
  from = "/blog/category/development"
  to = "/tags/development/"
  status = 301

[[redirects]]
  from = "/blog/tags/development/"
  to = "/tags/development/"
  status = 301

[[redirects]]
  from = "/blog/notes.php"
  to = "/notes/"
  status = 301

[[redirects]]
  from = "/rss"
  to = "/rss/feed.xml"
  status = 301

[[redirects]]
  from = "/blog/2016-12-09-adding-svg-icons-to-a-sprite-with-perch-cms/"
  to = "/blog/adding-svg-icons-to-a-sprite-with-perch-cms/"
  status = 301

[[redirects]]
  from = "/blog/2018-01-09-twenty-seventeen/"
  to = "/blog/twenty-seventeen/"
  status = 301

[[redirects]]
  from = "/blog/2019-04-16-weeknotes-10/"
  to = "/notes/weeknotes-10/"
  status = 301

[[redirects]]
  from = "/blog/exploring-the-benefits-if-http-2/"
  to = "/blog/exploring-the-benefits-of-http-2/"
  status = 301

[[redirects]]
  from = "/blog/2017-02-06-automatic-copyright-year-in-perch-cms"
  to = "/blog/automatic-copyright-year-in-perch-cms/"
  status = 301

[[redirects]]
  from = "/blog/2019-03-13-multiple-blogs-with-perch-cms"
  to = "/blog/multiple-blogs-with-perch-cms/"
  status = 301

[functions]
  external_node_modules = ["express", "vm2"]
  node_bundler = 'esbuild'
