---
new_page_extension: md
auto_deploy: false
admin_path: cms
webhook_url: 
sections:
- type: directory
  path: src/blog
  label: Blog
  create: all
  match: "**/*"
  new_doc_ext: md
- type: document
  path: src/now/now.md
  label: Now
- type: directory
  path: src/notes
  label: Notes
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - notes-post
- type: directory
  path: src/photos
  label: Photos
  create: documents
  match: "**/*"
  new_doc_ext: md
upload_dir: cms/imgs
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: grunt
