name: "11ty: Build and Deploy"

on:
  schedule:
    - cron: 0 2/6 * * *
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: "11ty: Build and Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            _cache/
            src/assets/imgs/
          key: 11ty-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            11ty-${{ runner.os }}
            ${{ runner.os }}-11ty
    
      - name: Install dependencies
        run: npm install

      - name: Append Instapaper links
        run: node src/_data/appendToJSON.js

      - name: Build website
        run: npm run build

      - name: Deploy website to server
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.CPANEL_HOST }}
          REMOTE_PORT: ${{ secrets.CPANEL_PORT }}
          REMOTE_USER: ${{ secrets.CPANEL_USER }}
          TARGET: ${{ secrets.CPANEL_TARGET }}
          EXCLUDE: ".git*, .github*, node_modules*, src*"

      - uses: actions/cache/save@v4
        with:
          path: |
            _cache/
            src/assets/imgs/
          key: 11ty-${{ runner.os }}-${{ github.run_id }}
