name: "11ty: Build and Deploy"

on:
  schedule:
    - cron: "0 0 * * *" # nightly
  push:
    branches: [ main ]
    paths:
      # Only run on pushes that touch your photos, the workflow, or key build files
      - 'src/photos/content/photos/**'
      - '.github/workflows/**'
      - '.eleventy.js'
      - 'package.json'
      - 'package-lock.json'
      - 'src/_data/**'

jobs:
  build-and-deploy:
    name: "11ty: Build and Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to diff changed files

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            _cache/
            src/assets/imgs/
          key: 11ty-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            11ty-${{ runner.os }}
            ${{ runner.os }}-11ty

      - name: Install dependencies
        run: npm install

      - name: Append Instapaper links
        run: node src/_data/appendToJSON.cjs

      - name: Build website
        run: npm run build

      # Create list of changed files (robust for push & schedule)
      - name: Get changed files
        id: diff
        run: |
          set -e
          git fetch --prune --unshallow || true
          BEFORE="${{ github.event.before }}"
          if [ -z "$BEFORE" ] || [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            BEFORE="$(git rev-parse HEAD~1)"
          fi
          echo "Diffing from $BEFORE to ${{ github.sha }}"
          git diff --name-only "$BEFORE" "${{ github.sha }}" > changed-files.txt
          echo "Changed files:"; cat changed-files.txt || true

      # Cross-post any new/changed photos to Pixelfed
      - name: Cross-post new photos to Pixelfed
        if: success()
        env:
          PIXELFED_BASE_URL: ${{ secrets.PIXELFED_BASE_URL }}
          PIXELFED_ACCESS_TOKEN: ${{ secrets.PIXELFED_ACCESS_TOKEN }}
        run: |
          set -e
          echo "Checking for changed photos…"
          # Exact folder + extensions (case-insensitive)
          if grep -iE '^src/photos/content/photos/.*\.(jpe?g|png|webp)$' changed-files.txt >/dev/null 2>&1; then
            echo "Photos changed, running sync…"
            node src/assets/js/pixelfed-sync.js changed-files.txt
          else
            echo "No changed photos detected, skipping Pixelfed sync."
          fi

      - name: Deploy website to server
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.CPANEL_HOST }}
          REMOTE_PORT: ${{ secrets.CPANEL_PORT }}
          REMOTE_USER: ${{ secrets.CPANEL_USER }}
          TARGET: ${{ secrets.CPANEL_TARGET }}
          EXCLUDE: ".git*, .github*, node_modules*, src*"

      - uses: actions/cache/save@v4
        with:
          path: |
            _cache/
            src/assets/imgs/
          key: 11ty-${{ runner.os }}-${{ github.run_id }}
