name: "11ty: Build and Deploy"

on:
  schedule:
    - cron: "0 0 * * *" # nightly
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  # ----------------------------------------------------------
  # Dry-run deploy preview on PRs (no changes on the server).
  # Note: Secrets are not exposed to PRs from forks, so the
  # SSH step is skipped unless the PR is from the same repo.
  # ----------------------------------------------------------
  deploy-dry-run:
    name: "11ty: Deploy (dry run on PR)"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            _cache/
            src/assets/imgs/
          key: 11ty-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            11ty-${{ runner.os }}
            ${{ runner.os }}-11ty

      - name: Install dependencies
        run: npm install

      - name: Append Instapaper links
        run: node src/_data/appendToJSON.cjs

      - name: Build website
        run: npm run build

      - name: Get changed files
        id: diff
        run: |
          set -e
          git fetch --prune --unshallow || true
          BEFORE="${{ github.event.before }}"
          if [ -z "$BEFORE" ] || [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            BEFORE="$(git rev-parse HEAD~1 || echo HEAD)"
          fi
          echo "Diffing from $BEFORE to ${{ github.sha }}"
          git diff --name-only "$BEFORE" "${{ github.sha }}" > changed-files.txt || true
          echo "Changed files:"; cat changed-files.txt || true

      # Skip Pixelfed on PRs to avoid side effects
      - name: Dry-run deploy (no server changes)
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository && secrets.CPANEL_SSH_KEY }}
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.CPANEL_HOST }}
          REMOTE_PORT: ${{ secrets.CPANEL_PORT }}
          REMOTE_USER: ${{ secrets.CPANEL_USER }}
          TARGET: ${{ secrets.CPANEL_TARGET }}
          EXCLUDE: ".git*, .github*, node_modules*, src*"
          # -n / --dry-run previews changes; --delete shows which files would be removed
          ARGS: "-rlgoDzvc -i --delete --dry-run"

      - uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            _cache/
            src/assets/imgs/
          key: 11ty-${{ runner.os }}-${{ github.run_id }}

  # ----------------------------------------------------------
  # Real build & deploy on push/schedule
  # ----------------------------------------------------------
  build-and-deploy:
    name: "11ty: Build and Deploy"
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to diff changed files

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            _cache/
            src/assets/imgs/
          key: 11ty-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            11ty-${{ runner.os }}
            ${{ runner.os }}-11ty

      - name: Install dependencies
        run: npm install

      - name: Append Instapaper links
        run: node src/_data/appendToJSON.cjs

      - name: Build website
        run: npm run build

      - name: Get changed files
        id: diff
        run: |
          set -e
          git fetch --prune --unshallow || true
          BEFORE="${{ github.event.before }}"
          if [ -z "$BEFORE" ] || [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            BEFORE="$(git rev-parse HEAD~1)"
          fi
          echo "Diffing from $BEFORE to ${{ github.sha }}"
          git diff --name-only "$BEFORE" "${{ github.sha }}" > changed-files.txt
          echo "Changed files:"; cat changed-files.txt || true

      # Cross-post any new/changed photos to Pixelfed
      - name: Cross-post new photos to Pixelfed
        if: success()
        env:
          PIXELFED_BASE_URL: ${{ secrets.PIXELFED_BASE_URL }}
          PIXELFED_ACCESS_TOKEN: ${{ secrets.PIXELFED_ACCESS_TOKEN }}
        run: |
          set -e
          echo "Checking for changed photos…"
          if grep -iE '^photos/content/photos/.*\.(jpe?g|png|webp)$' changed-files.txt >/dev/null 2>&1; then
            echo "Photos changed, running sync…"
            node src/assets/js/pixelfed-sync.js changed-files.txt
          else
            echo "No changed photos detected, skipping Pixelfed sync."
          fi

      - name: Deploy website to server
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_KEY }}
          SOURCE: "dist/"                # trailing slash = contents only
          REMOTE_HOST: ${{ secrets.CPANEL_HOST }}
          REMOTE_PORT: ${{ secrets.CPANEL_PORT }}
          REMOTE_USER: ${{ secrets.CPANEL_USER }}
          TARGET: ${{ secrets.CPANEL_TARGET }}
          EXCLUDE: ".git*, .github*, node_modules*, src*"
          ARGS: "-rlgoDzvc -i --delete"  # mirror deletions on server

      - uses: actions/cache/save@v4
        with:
          path: |
            _cache/
            src/assets/imgs/
          key: 11ty-${{ runner.os }}-${{ github.run_id }}
